//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuppliersDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuppliersDashboard.Resources.layout", typeof(layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills This Month.
        /// </summary>
        public static string billsthismonth {
            get {
                return ResourceManager.GetString("billsthismonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlankPage.
        /// </summary>
        public static string blankpage {
            get {
                return ResourceManager.GetString("blankpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        public static string buttons {
            get {
                return ResourceManager.GetString("buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        public static string distributors {
            get {
                return ResourceManager.GetString("distributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password ? .
        /// </summary>
        public static string forget_password {
            get {
                return ResourceManager.GetString("forget password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string forms {
            get {
                return ResourceManager.GetString("forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets.
        /// </summary>
        public static string markets {
            get {
                return ResourceManager.GetString("markets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account .
        /// </summary>
        public static string new_account {
            get {
                return ResourceManager.GetString("new account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Elements.
        /// </summary>
        public static string otherelemnts {
            get {
                return ResourceManager.GetString("otherelemnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string pages {
            get {
                return ResourceManager.GetString("pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phonenumber {
            get {
                return ResourceManager.GetString("phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Count.
        /// </summary>
        public static string productcount {
            get {
                return ResourceManager.GetString("productcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Requests.
        /// </summary>
        public static string regreguest {
            get {
                return ResourceManager.GetString("regreguest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string suppliers {
            get {
                return ResourceManager.GetString("suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Dashboard.
        /// </summary>
        public static string suppliersdashboard {
            get {
                return ResourceManager.GetString("suppliersdashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string tables {
            get {
                return ResourceManager.GetString("tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typography.
        /// </summary>
        public static string typography {
            get {
                return ResourceManager.GetString("typography", resourceCulture);
            }
        }
    }
}
