//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuppliersDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class llayout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal llayout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuppliersDashboard.Resources.llayout", typeof(llayout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative account statement.
        /// </summary>
        public static string accentof {
            get {
                return ResourceManager.GetString("accentof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account statement.
        /// </summary>
        public static string Account_statement {
            get {
                return ResourceManager.GetString("Account_statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer statement page.
        /// </summary>
        public static string AccountCutomer {
            get {
                return ResourceManager.GetString("AccountCutomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor&apos;s statement.
        /// </summary>
        public static string AccountDis {
            get {
                return ResourceManager.GetString("AccountDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountss.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Channel.
        /// </summary>
        public static string Add_Channel {
            get {
                return ResourceManager.GetString("Add_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        public static string Add_Customer {
            get {
                return ResourceManager.GetString("Add_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Distributors Group.
        /// </summary>
        public static string Add_Distributors_Group {
            get {
                return ResourceManager.GetString("Add_Distributors_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add opening balance.
        /// </summary>
        public static string Add_opening_balance {
            get {
                return ResourceManager.GetString("Add_opening_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Or Edit Or Stop Item.
        /// </summary>
        public static string Add_Or_Stop_Item {
            get {
                return ResourceManager.GetString("Add_Or_Stop_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Region Or Neighborhood.
        /// </summary>
        public static string Add_Region_Or_neighborhood {
            get {
                return ResourceManager.GetString("Add_Region_Or_neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        public static string Add_Supplier {
            get {
                return ResourceManager.GetString("Add_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and Edit Agents.
        /// </summary>
        public static string addandeditagents {
            get {
                return ResourceManager.GetString("addandeditagents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bank.
        /// </summary>
        public static string addbank {
            get {
                return ResourceManager.GetString("addbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customers.
        /// </summary>
        public static string addCustomer {
            get {
                return ResourceManager.GetString("addCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Items.
        /// </summary>
        public static string additems {
            get {
                return ResourceManager.GetString("additems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        public static string addsupplier {
            get {
                return ResourceManager.GetString("addsupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add warehouse request.
        /// </summary>
        public static string Addwarehouserequest {
            get {
                return ResourceManager.GetString("Addwarehouserequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distributors.
        /// </summary>
        public static string Alldelegates {
            get {
                return ResourceManager.GetString("Alldelegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Groups.
        /// </summary>
        public static string AllGroups {
            get {
                return ResourceManager.GetString("AllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sales Count.
        /// </summary>
        public static string AllSalesCount {
            get {
                return ResourceManager.GetString("AllSalesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount required.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.
        /// </summary>
        public static string Amount1 {
            get {
                return ResourceManager.GetString("Amount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrears.
        /// </summary>
        public static string arrears {
            get {
                return ResourceManager.GetString("arrears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Sale.
        /// </summary>
        public static string assalesman {
            get {
                return ResourceManager.GetString("assalesman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Number.
        /// </summary>
        public static string billNo {
            get {
                return ResourceManager.GetString("billNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Bills.
        /// </summary>
        public static string billsearch {
            get {
                return ResourceManager.GetString("billsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills This Month.
        /// </summary>
        public static string billsthismonth {
            get {
                return ResourceManager.GetString("billsthismonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlankPage.
        /// </summary>
        public static string blankpage {
            get {
                return ResourceManager.GetString("blankpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BranchsReports.
        /// </summary>
        public static string BranchReports {
            get {
                return ResourceManager.GetString("BranchReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        public static string buttons {
            get {
                return ResourceManager.GetString("buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Bill.
        /// </summary>
        public static string cashBill {
            get {
                return ResourceManager.GetString("cashBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check number.
        /// </summary>
        public static string checknumber {
            get {
                return ResourceManager.GetString("checknumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update  Checks.
        /// </summary>
        public static string Checks {
            get {
                return ResourceManager.GetString("Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Representative.
        /// </summary>
        public static string ChooseRepresentative {
            get {
                return ResourceManager.GetString("ChooseRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing today&apos;s account for the representative.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cash.
        /// </summary>
        public static string Clearcash {
            get {
                return ResourceManager.GetString("Clearcash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients of this representative.
        /// </summary>
        public static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close today.
        /// </summary>
        public static string closetoday {
            get {
                return ResourceManager.GetString("closetoday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission_project.
        /// </summary>
        public static string Commission_project {
            get {
                return ResourceManager.GetString("Commission_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company code.
        /// </summary>
        public static string companycode {
            get {
                return ResourceManager.GetString("companycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm receipt of the amount.
        /// </summary>
        public static string Confirmre {
            get {
                return ResourceManager.GetString("Confirmre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Reports.
        /// </summary>
        public static string CorporateReports {
            get {
                return ResourceManager.GetString("CorporateReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covenants.
        /// </summary>
        public static string covenant {
            get {
                return ResourceManager.GetString("covenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Percentage.
        /// </summary>
        public static string CurrentPercentage {
            get {
                return ResourceManager.GetString("CurrentPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        public static string Customer_Details {
            get {
                return ResourceManager.GetString("Customer_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Classification.
        /// </summary>
        public static string CustomerClassification {
            get {
                return ResourceManager.GetString("CustomerClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor Customer Page.
        /// </summary>
        public static string Customerpage {
            get {
                return ResourceManager.GetString("Customerpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Achieved Bill Amount.
        /// </summary>
        public static string DailyAchievedBillAmount {
            get {
                return ResourceManager.GetString("DailyAchievedBillAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Percentage.
        /// </summary>
        public static string DailyPercentage {
            get {
                return ResourceManager.GetString("DailyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Target Amount.
        /// </summary>
        public static string DailyTargetAmount {
            get {
                return ResourceManager.GetString("DailyTargetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required.
        /// </summary>
        public static string Daterequired {
            get {
                return ResourceManager.GetString("Daterequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashborad Suppliers.
        /// </summary>
        public static string dawar {
            get {
                return ResourceManager.GetString("dawar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Men.
        /// </summary>
        public static string dawarSalesMen {
            get {
                return ResourceManager.GetString("dawarSalesMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deficit of payment papers.
        /// </summary>
        public static string Deficitpaymentpapers {
            get {
                return ResourceManager.GetString("Deficitpaymentpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deficit of defferedpapers.
        /// </summary>
        public static string Deficitpaymentpapers1 {
            get {
                return ResourceManager.GetString("Deficitpaymentpapers1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distributor  management.
        /// </summary>
        public static string Delegatemanagement {
            get {
                return ResourceManager.GetString("Delegatemanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate Reports.
        /// </summary>
        public static string DelegateReports {
            get {
                return ResourceManager.GetString("DelegateReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Is Not rem.
        /// </summary>
        public static string dets {
            get {
                return ResourceManager.GetString("dets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor Management Page.
        /// </summary>
        public static string Distributorpage {
            get {
                return ResourceManager.GetString("Distributorpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        public static string distributors {
            get {
                return ResourceManager.GetString("distributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors Details.
        /// </summary>
        public static string Distributors_Details {
            get {
                return ResourceManager.GetString("Distributors_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors Sales.
        /// </summary>
        public static string Distributors_Sales {
            get {
                return ResourceManager.GetString("Distributors_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download excel.
        /// </summary>
        public static string Downloadexcel {
            get {
                return ResourceManager.GetString("Downloadexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item sales to representatives and customers.
        /// </summary>
        public static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Channel.
        /// </summary>
        public static string Edit_Channel {
            get {
                return ResourceManager.GetString("Edit_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer Details.
        /// </summary>
        public static string Edit_Customer_Details {
            get {
                return ResourceManager.GetString("Edit_Customer_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Or Stop Supplier.
        /// </summary>
        public static string Edit_Or_Stop_Supplier {
            get {
                return ResourceManager.GetString("Edit_Or_Stop_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Prices For Factory.
        /// </summary>
        public static string Edit_Prices {
            get {
                return ResourceManager.GetString("Edit_Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing data.
        /// </summary>
        public static string Editingdata {
            get {
                return ResourceManager.GetString("Editingdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Company Data.
        /// </summary>
        public static string EditoCompanyData {
            get {
                return ResourceManager.GetString("EditoCompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DawnLoad Execl.
        /// </summary>
        public static string Execl {
            get {
                return ResourceManager.GetString("Execl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Bill Man .
        /// </summary>
        public static string FirstBillManName {
            get {
                return ResourceManager.GetString("FirstBillManName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Visit.
        /// </summary>
        public static string FirstVisit {
            get {
                return ResourceManager.GetString("FirstVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password ? .
        /// </summary>
        public static string forget_password {
            get {
                return ResourceManager.GetString("forget password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string forms {
            get {
                return ResourceManager.GetString("forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales of bundled items.
        /// </summary>
        public static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Products To Representative.
        /// </summary>
        public static string Give_Products_To_Representative {
            get {
                return ResourceManager.GetString("Give_Products_To_Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Sale.
        /// </summary>
        public static string Group_Sale {
            get {
                return ResourceManager.GetString("Group_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Total Sale.
        /// </summary>
        public static string Group_Total_Sale {
            get {
                return ResourceManager.GetString("Group_Total_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print.
        /// </summary>
        public static string HeaderAcount {
            get {
                return ResourceManager.GetString("HeaderAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inability.
        /// </summary>
        public static string inability {
            get {
                return ResourceManager.GetString("inability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indebtedness.
        /// </summary>
        public static string Indebtedness {
            get {
                return ResourceManager.GetString("Indebtedness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        public static string integration {
            get {
                return ResourceManager.GetString("integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory of accounts.
        /// </summary>
        public static string Inventory_of_accounts {
            get {
                return ResourceManager.GetString("Inventory_of_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice totals.
        /// </summary>
        public static string Invoice_totals {
            get {
                return ResourceManager.GetString("Invoice_totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice arrears.
        /// </summary>
        public static string Invoicearrears {
            get {
                return ResourceManager.GetString("Invoicearrears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item_ID.
        /// </summary>
        public static string Item_ID {
            get {
                return ResourceManager.GetString("Item_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Sale.
        /// </summary>
        public static string Item_Sale {
            get {
                return ResourceManager.GetString("Item_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Total Sale.
        /// </summary>
        public static string Item_Total_Sale {
            get {
                return ResourceManager.GetString("Item_Total_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Transaction.
        /// </summary>
        public static string Item_Transaction {
            get {
                return ResourceManager.GetString("Item_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Details.
        /// </summary>
        public static string Items_Details {
            get {
                return ResourceManager.GetString("Items_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors Items Setting .
        /// </summary>
        public static string itemsdistributorssetting {
            get {
                return ResourceManager.GetString("itemsdistributorssetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Setting .
        /// </summary>
        public static string itemssetting {
            get {
                return ResourceManager.GetString("itemssetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keepers and Accounters Reports.
        /// </summary>
        public static string keepers_and_Accounters_Reports {
            get {
                return ResourceManager.GetString("keepers and Accounters Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string loginusername {
            get {
                return ResourceManager.GetString("loginusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets.
        /// </summary>
        public static string markets {
            get {
                return ResourceManager.GetString("markets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money shortage.
        /// </summary>
        public static string Moneyshortage {
            get {
                return ResourceManager.GetString("Moneyshortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly delegate.
        /// </summary>
        public static string Monthlydelegate {
            get {
                return ResourceManager.GetString("Monthlydelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Sales Man.
        /// </summary>
        public static string NameSalesMan {
            get {
                return ResourceManager.GetString("NameSalesMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account .
        /// </summary>
        public static string new_account {
            get {
                return ResourceManager.GetString("new account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no information yet.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no categories.
        /// </summary>
        public static string nocategories {
            get {
                return ResourceManager.GetString("nocategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open account.
        /// </summary>
        public static string openaccount {
            get {
                return ResourceManager.GetString("openaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string operations {
            get {
                return ResourceManager.GetString("operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Elements.
        /// </summary>
        public static string otherelemnts {
            get {
                return ResourceManager.GetString("otherelemnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string pages {
            get {
                return ResourceManager.GetString("pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment papers.
        /// </summary>
        public static string Paymentpapers {
            get {
                return ResourceManager.GetString("Paymentpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phonenumber {
            get {
                return ResourceManager.GetString("phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill All Fields .
        /// </summary>
        public static string plzfillallfields {
            get {
                return ResourceManager.GetString("plzfillallfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and Update .
        /// </summary>
        public static string PriceListSetting {
            get {
                return ResourceManager.GetString("PriceListSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices Details.
        /// </summary>
        public static string Prices_Details {
            get {
                return ResourceManager.GetString("Prices_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price total.
        /// </summary>
        public static string pricetotel {
            get {
                return ResourceManager.GetString("pricetotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productcode.
        /// </summary>
        public static string pro {
            get {
                return ResourceManager.GetString("pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Count.
        /// </summary>
        public static string productcount {
            get {
                return ResourceManager.GetString("productcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranges.
        /// </summary>
        public static string Ranges {
            get {
                return ResourceManager.GetString("Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receivable papers.
        /// </summary>
        public static string Receivablepapers {
            get {
                return ResourceManager.GetString("Receivablepapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Products To Representative.
        /// </summary>
        public static string Receive_Products_To_Representative {
            get {
                return ResourceManager.GetString("Receive_Products_To_Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received amount.
        /// </summary>
        public static string Receivedamount {
            get {
                return ResourceManager.GetString("Receivedamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Requests.
        /// </summary>
        public static string regreguest {
            get {
                return ResourceManager.GetString("regreguest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management {0} Distributors.
        /// </summary>
        public static string Representative_management {
            get {
                return ResourceManager.GetString("Representative_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative performance analysis.
        /// </summary>
        public static string Representativeperformanceanalysis {
            get {
                return ResourceManager.GetString("Representativeperformanceanalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative is required.
        /// </summary>
        public static string Representativerequired {
            get {
                return ResourceManager.GetString("Representativerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Request.
        /// </summary>
        public static string reqest {
            get {
                return ResourceManager.GetString("reqest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable Person.
        /// </summary>
        public static string responsobileperson {
            get {
                return ResourceManager.GetString("responsobileperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved .
        /// </summary>
        public static string rights {
            get {
                return ResourceManager.GetString("rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling items by delegate.
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Reports.
        /// </summary>
        public static string SafeReports {
            get {
                return ResourceManager.GetString("SafeReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sale.
        /// </summary>
        public static string sale {
            get {
                return ResourceManager.GetString("sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell ​​to a sales channel.
        /// </summary>
        public static string saleChannHead {
            get {
                return ResourceManager.GetString("saleChannHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Channels.
        /// </summary>
        public static string Sales_channels {
            get {
                return ResourceManager.GetString("Sales_channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Channel Reports.
        /// </summary>
        public static string SalesChannelReports {
            get {
                return ResourceManager.GetString("SalesChannelReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Count Has Bill.
        /// </summary>
        public static string SalesCountHasBill {
            get {
                return ResourceManager.GetString("SalesCountHasBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Count Has Item.
        /// </summary>
        public static string SalesCountHasItem {
            get {
                return ResourceManager.GetString("SalesCountHasItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Man Classification.
        /// </summary>
        public static string SalesManClassification {
            get {
                return ResourceManager.GetString("SalesManClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Of Client.
        /// </summary>
        public static string SalesOfClient {
            get {
                return ResourceManager.GetString("SalesOfClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Visit.
        /// </summary>
        public static string SecondVisit {
            get {
                return ResourceManager.GetString("SecondVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to distruber.
        /// </summary>
        public static string selectd {
            get {
                return ResourceManager.GetString("selectd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select of product.
        /// </summary>
        public static string selectp {
            get {
                return ResourceManager.GetString("selectp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the delegate.
        /// </summary>
        public static string Selectthedelegate {
            get {
                return ResourceManager.GetString("Selectthedelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Invoice.
        /// </summary>
        public static string sendBill {
            get {
                return ResourceManager.GetString("sendBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settle Returns.
        /// </summary>
        public static string SettleReturns {
            get {
                return ResourceManager.GetString("SettleReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieve / Give shift.
        /// </summary>
        public static string shift {
            get {
                return ResourceManager.GetString("shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortfall payment.
        /// </summary>
        public static string shortfallpayment {
            get {
                return ResourceManager.GetString("shortfallpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shortfall deffered.
        /// </summary>
        public static string shortfallpayment1 {
            get {
                return ResourceManager.GetString("shortfallpayment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Prices.
        /// </summary>
        public static string Special_Prices {
            get {
                return ResourceManager.GetString("Special_Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopSupplier.
        /// </summary>
        public static string stopsupplier {
            get {
                return ResourceManager.GetString("stopsupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store keeper.
        /// </summary>
        public static string Storekeeper {
            get {
                return ResourceManager.GetString("Storekeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Requests.
        /// </summary>
        public static string storerequests {
            get {
                return ResourceManager.GetString("storerequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store shortage.
        /// </summary>
        public static string Storeshortage {
            get {
                return ResourceManager.GetString("Storeshortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of term papers.
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of term papers.
        /// </summary>
        public static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of arrest notes.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of arrest papers.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-store inventory.
        /// </summary>
        public static string sub {
            get {
                return ResourceManager.GetString("sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supplier.
        /// </summary>
        public static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string suppliers {
            get {
                return ResourceManager.GetString("suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Dashboard.
        /// </summary>
        public static string suppliersdashboard {
            get {
                return ResourceManager.GetString("suppliersdashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string tables {
            get {
                return ResourceManager.GetString("tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term papers.
        /// </summary>
        public static string Termpapers {
            get {
                return ResourceManager.GetString("Termpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Safe.
        /// </summary>
        public static string the_safe {
            get {
                return ResourceManager.GetString("the_safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Visit.
        /// </summary>
        public static string ThirdVisit {
            get {
                return ResourceManager.GetString("ThirdVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Collection.
        /// </summary>
        public static string TotalCollection {
            get {
                return ResourceManager.GetString("TotalCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total payment.
        /// </summary>
        public static string Totalpayment {
            get {
                return ResourceManager.GetString("Totalpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total deffered.
        /// </summary>
        public static string Totalpayment1 {
            get {
                return ResourceManager.GetString("Totalpayment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Remaining.
        /// </summary>
        public static string TotalRemaining {
            get {
                return ResourceManager.GetString("TotalRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales Amount.
        /// </summary>
        public static string TotalSalesAmount {
            get {
                return ResourceManager.GetString("TotalSalesAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranfere Items Between Two WareHouses.
        /// </summary>
        public static string TranfereItemsBetweenTwoWareHouses {
            get {
                return ResourceManager.GetString("TranfereItemsBetweenTwoWareHouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typography.
        /// </summary>
        public static string typography {
            get {
                return ResourceManager.GetString("typography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Price For Items.
        /// </summary>
        public static string updateprice {
            get {
                return ResourceManager.GetString("updateprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update price .
        /// </summary>
        public static string updatepriceforpricelist {
            get {
                return ResourceManager.GetString("updatepriceforpricelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prices Groups.
        /// </summary>
        public static string updatepricesfordisgroups {
            get {
                return ResourceManager.GetString("updatepricesfordisgroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        public static string Users_Management {
            get {
                return ResourceManager.GetString("Users_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow a client visit.
        /// </summary>
        public static string visitofcustomer {
            get {
                return ResourceManager.GetString("visitofcustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ware House Review.
        /// </summary>
        public static string Ware_House_Review {
            get {
                return ResourceManager.GetString("Ware_House_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WareHouse.
        /// </summary>
        public static string wareHouse {
            get {
                return ResourceManager.GetString("wareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and Update WareHouses.
        /// </summary>
        public static string WareHousesSetting {
            get {
                return ResourceManager.GetString("WareHousesSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
    }
}
