//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuppliersDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class llayout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal llayout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuppliersDashboard.Resources.llayout", typeof(llayout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account statement.
        /// </summary>
        public static string Account_statement {
            get {
                return ResourceManager.GetString("Account_statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Channel.
        /// </summary>
        public static string Add_Channel {
            get {
                return ResourceManager.GetString("Add_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        public static string Add_Customer {
            get {
                return ResourceManager.GetString("Add_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Distributors Group.
        /// </summary>
        public static string Add_Distributors_Group {
            get {
                return ResourceManager.GetString("Add_Distributors_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add opening balance.
        /// </summary>
        public static string Add_opening_balance {
            get {
                return ResourceManager.GetString("Add_opening_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Or Stop Item.
        /// </summary>
        public static string Add_Or_Stop_Item {
            get {
                return ResourceManager.GetString("Add_Or_Stop_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Region Or Neighborhood.
        /// </summary>
        public static string Add_Region_Or_neighborhood {
            get {
                return ResourceManager.GetString("Add_Region_Or_neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        public static string Add_Supplier {
            get {
                return ResourceManager.GetString("Add_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and Edit Agents.
        /// </summary>
        public static string addandeditagents {
            get {
                return ResourceManager.GetString("addandeditagents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bank.
        /// </summary>
        public static string addbank {
            get {
                return ResourceManager.GetString("addbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Items.
        /// </summary>
        public static string additems {
            get {
                return ResourceManager.GetString("additems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        public static string addsupplier {
            get {
                return ResourceManager.GetString("addsupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Number.
        /// </summary>
        public static string billNo {
            get {
                return ResourceManager.GetString("billNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills This Month.
        /// </summary>
        public static string billsthismonth {
            get {
                return ResourceManager.GetString("billsthismonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlankPage.
        /// </summary>
        public static string blankpage {
            get {
                return ResourceManager.GetString("blankpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        public static string buttons {
            get {
                return ResourceManager.GetString("buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        public static string Customer_Details {
            get {
                return ResourceManager.GetString("Customer_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        public static string distributors {
            get {
                return ResourceManager.GetString("distributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors Details.
        /// </summary>
        public static string Distributors_Details {
            get {
                return ResourceManager.GetString("Distributors_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors Sales.
        /// </summary>
        public static string Distributors_Sales {
            get {
                return ResourceManager.GetString("Distributors_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Channel.
        /// </summary>
        public static string Edit_Channel {
            get {
                return ResourceManager.GetString("Edit_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer Details.
        /// </summary>
        public static string Edit_Customer_Details {
            get {
                return ResourceManager.GetString("Edit_Customer_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Or Stop Supplier.
        /// </summary>
        public static string Edit_Or_Stop_Supplier {
            get {
                return ResourceManager.GetString("Edit_Or_Stop_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Prices.
        /// </summary>
        public static string Edit_Prices {
            get {
                return ResourceManager.GetString("Edit_Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password ? .
        /// </summary>
        public static string forget_password {
            get {
                return ResourceManager.GetString("forget password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string forms {
            get {
                return ResourceManager.GetString("forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Products To Representative.
        /// </summary>
        public static string Give_Products_To_Representative {
            get {
                return ResourceManager.GetString("Give_Products_To_Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Sale.
        /// </summary>
        public static string Group_Sale {
            get {
                return ResourceManager.GetString("Group_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Total Sale.
        /// </summary>
        public static string Group_Total_Sale {
            get {
                return ResourceManager.GetString("Group_Total_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indebtedness.
        /// </summary>
        public static string Indebtedness {
            get {
                return ResourceManager.GetString("Indebtedness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        public static string integration {
            get {
                return ResourceManager.GetString("integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory of accounts.
        /// </summary>
        public static string Inventory_of_accounts {
            get {
                return ResourceManager.GetString("Inventory_of_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice totals.
        /// </summary>
        public static string Invoice_totals {
            get {
                return ResourceManager.GetString("Invoice_totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Sale.
        /// </summary>
        public static string Item_Sale {
            get {
                return ResourceManager.GetString("Item_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Total Sale.
        /// </summary>
        public static string Item_Total_Sale {
            get {
                return ResourceManager.GetString("Item_Total_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Transaction.
        /// </summary>
        public static string Item_Transaction {
            get {
                return ResourceManager.GetString("Item_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Details.
        /// </summary>
        public static string Items_Details {
            get {
                return ResourceManager.GetString("Items_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors Items Setting .
        /// </summary>
        public static string itemsdistributorssetting {
            get {
                return ResourceManager.GetString("itemsdistributorssetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Setting .
        /// </summary>
        public static string itemssetting {
            get {
                return ResourceManager.GetString("itemssetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string loginusername {
            get {
                return ResourceManager.GetString("loginusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets.
        /// </summary>
        public static string markets {
            get {
                return ResourceManager.GetString("markets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account .
        /// </summary>
        public static string new_account {
            get {
                return ResourceManager.GetString("new account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string operations {
            get {
                return ResourceManager.GetString("operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Elements.
        /// </summary>
        public static string otherelemnts {
            get {
                return ResourceManager.GetString("otherelemnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string pages {
            get {
                return ResourceManager.GetString("pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phonenumber {
            get {
                return ResourceManager.GetString("phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill All Fields .
        /// </summary>
        public static string plzfillallfields {
            get {
                return ResourceManager.GetString("plzfillallfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices Details.
        /// </summary>
        public static string Prices_Details {
            get {
                return ResourceManager.GetString("Prices_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Count.
        /// </summary>
        public static string productcount {
            get {
                return ResourceManager.GetString("productcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Products To Representative.
        /// </summary>
        public static string Receive_Products_To_Representative {
            get {
                return ResourceManager.GetString("Receive_Products_To_Representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration Requests.
        /// </summary>
        public static string regreguest {
            get {
                return ResourceManager.GetString("regreguest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management {0} Distributors.
        /// </summary>
        public static string Representative_management {
            get {
                return ResourceManager.GetString("Representative_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Request.
        /// </summary>
        public static string reqest {
            get {
                return ResourceManager.GetString("reqest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable Person.
        /// </summary>
        public static string responsobileperson {
            get {
                return ResourceManager.GetString("responsobileperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved .
        /// </summary>
        public static string rights {
            get {
                return ResourceManager.GetString("rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sale.
        /// </summary>
        public static string sale {
            get {
                return ResourceManager.GetString("sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Channels.
        /// </summary>
        public static string Sales_channels {
            get {
                return ResourceManager.GetString("Sales_channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Invoice.
        /// </summary>
        public static string sendBill {
            get {
                return ResourceManager.GetString("sendBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieve / Give shift.
        /// </summary>
        public static string shift {
            get {
                return ResourceManager.GetString("shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Prices.
        /// </summary>
        public static string Special_Prices {
            get {
                return ResourceManager.GetString("Special_Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopSupplier.
        /// </summary>
        public static string stopsupplier {
            get {
                return ResourceManager.GetString("stopsupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Requests.
        /// </summary>
        public static string storerequests {
            get {
                return ResourceManager.GetString("storerequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string suppliers {
            get {
                return ResourceManager.GetString("suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Dashboard.
        /// </summary>
        public static string suppliersdashboard {
            get {
                return ResourceManager.GetString("suppliersdashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string tables {
            get {
                return ResourceManager.GetString("tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Safe.
        /// </summary>
        public static string the_safe {
            get {
                return ResourceManager.GetString("the_safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typography.
        /// </summary>
        public static string typography {
            get {
                return ResourceManager.GetString("typography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        public static string Users_Management {
            get {
                return ResourceManager.GetString("Users_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ware House Review.
        /// </summary>
        public static string Ware_House_Review {
            get {
                return ResourceManager.GetString("Ware_House_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WareHouse.
        /// </summary>
        public static string wareHouse {
            get {
                return ResourceManager.GetString("wareHouse", resourceCulture);
            }
        }
    }
}
