//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuppliersDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuppliersDashboard.Resources.pages", typeof(pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the period from.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account statement.
        /// </summary>
        public static string accountstatement {
            get {
                return ResourceManager.GetString("accountstatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate.
        /// </summary>
        public static string activate {
            get {
                return ResourceManager.GetString("activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualquantity.
        /// </summary>
        public static string Actualquantity {
            get {
                return ResourceManager.GetString("Actualquantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Agent.
        /// </summary>
        public static string addagent {
            get {
                return ResourceManager.GetString("addagent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and Edit Agents and Supervisorsa.
        /// </summary>
        public static string addandeditagent {
            get {
                return ResourceManager.GetString("addandeditagent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Date.
        /// </summary>
        public static string adddate {
            get {
                return ResourceManager.GetString("adddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add discount.
        /// </summary>
        public static string adddiscount {
            get {
                return ResourceManager.GetString("adddiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        public static string addedsuccess {
            get {
                return ResourceManager.GetString("addedsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string Additem {
            get {
                return ResourceManager.GetString("Additem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Channel.
        /// </summary>
        public static string addnewagent {
            get {
                return ResourceManager.GetString("addnewagent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supervisor.
        /// </summary>
        public static string addsupervisor {
            get {
                return ResourceManager.GetString("addsupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supervisor To .
        /// </summary>
        public static string addsupervisortoagent {
            get {
                return ResourceManager.GetString("addsupervisortoagent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an expense type.
        /// </summary>
        public static string addtypeex {
            get {
                return ResourceManager.GetString("addtypeex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents.
        /// </summary>
        public static string agents {
            get {
                return ResourceManager.GetString("agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total actions.
        /// </summary>
        public static string allaction {
            get {
                return ResourceManager.GetString("allaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Details.
        /// </summary>
        public static string alldetails {
            get {
                return ResourceManager.GetString("alldetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount required.
        /// </summary>
        public static string amountrequired {
            get {
                return ResourceManager.GetString("amountrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area name.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillNo .
        /// </summary>
        public static string billno {
            get {
                return ResourceManager.GetString("billno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string bills {
            get {
                return ResourceManager.GetString("bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string cash {
            get {
                return ResourceManager.GetString("cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        public static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose supplier.
        /// </summary>
        public static string chhosesupplier {
            get {
                return ResourceManager.GetString("chhosesupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a distributor.
        /// </summary>
        public static string Chooseadistributor {
            get {
                return ResourceManager.GetString("Chooseadistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose category.
        /// </summary>
        public static string choosecategory {
            get {
                return ResourceManager.GetString("choosecategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose supplier.
        /// </summary>
        public static string choosesupplier {
            get {
                return ResourceManager.GetString("choosesupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect.
        /// </summary>
        public static string Collect {
            get {
                return ResourceManager.GetString("Collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string collection {
            get {
                return ResourceManager.GetString("collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Amount .
        /// </summary>
        public static string collectionamount {
            get {
                return ResourceManager.GetString("collectionamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor.
        /// </summary>
        public static string cond {
            get {
                return ResourceManager.GetString("cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current balance.
        /// </summary>
        public static string currentbalance {
            get {
                return ResourceManager.GetString("currentbalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer name.
        /// </summary>
        public static string customername {
            get {
                return ResourceManager.GetString("customername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al-Dawar Dairy Products.
        /// </summary>
        public static string dawarmalik {
            get {
                return ResourceManager.GetString("dawarmalik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days of stopping collection.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deactivate.
        /// </summary>
        public static string deactivate {
            get {
                return ResourceManager.GetString("deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default quantity.
        /// </summary>
        public static string Defaultquantity {
            get {
                return ResourceManager.GetString("Defaultquantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deffered.
        /// </summary>
        public static string deffered {
            get {
                return ResourceManager.GetString("deffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay days.
        /// </summary>
        public static string Delaydays {
            get {
                return ResourceManager.GetString("Delaydays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string deletesuccess {
            get {
                return ResourceManager.GetString("deletesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismissed.
        /// </summary>
        public static string Dismissed {
            get {
                return ResourceManager.GetString("Dismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        public static string distributor {
            get {
                return ResourceManager.GetString("distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        public static string distributors {
            get {
                return ResourceManager.GetString("distributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        public static string distributorsgroup {
            get {
                return ResourceManager.GetString("distributorsgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Successfully.
        /// </summary>
        public static string editedsucces {
            get {
                return ResourceManager.GetString("editedsucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Supervisor.
        /// </summary>
        public static string editsupervisor {
            get {
                return ResourceManager.GetString("editsupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange license number.
        /// </summary>
        public static string ex {
            get {
                return ResourceManager.GetString("ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense reports.
        /// </summary>
        public static string Expensereports {
            get {
                return ResourceManager.GetString("Expensereports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string groupname {
            get {
                return ResourceManager.GetString("groupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupUser.
        /// </summary>
        public static string GroupUser {
            get {
                return ResourceManager.GetString("GroupUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Users.
        /// </summary>
        public static string groupusers {
            get {
                return ResourceManager.GetString("groupusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string iin {
            get {
                return ResourceManager.GetString("iin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impotence.
        /// </summary>
        public static string Impotence {
            get {
                return ResourceManager.GetString("Impotence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        public static string Incoming {
            get {
                return ResourceManager.GetString("Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside the warehouse.
        /// </summary>
        public static string inside {
            get {
                return ResourceManager.GetString("inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice value.
        /// </summary>
        public static string Invoicevalue {
            get {
                return ResourceManager.GetString("Invoicevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this page is to change items price or disable specific item to specific group of distributors.
        /// </summary>
        public static string itempagedescription {
            get {
                return ResourceManager.GetString("itempagedescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late customers.
        /// </summary>
        public static string latecustomer {
            get {
                return ResourceManager.GetString("latecustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loss.
        /// </summary>
        public static string loss {
            get {
                return ResourceManager.GetString("loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an invoice.
        /// </summary>
        public static string makeinvoice {
            get {
                return ResourceManager.GetString("makeinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Group.
        /// </summary>
        public static string managegroup {
            get {
                return ResourceManager.GetString("managegroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to measruing unit.
        /// </summary>
        public static string measruingunit {
            get {
                return ResourceManager.GetString("measruingunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment method.
        /// </summary>
        public static string method {
            get {
                return ResourceManager.GetString("method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement type.
        /// </summary>
        public static string Movementtype {
            get {
                return ResourceManager.GetString("Movementtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masrofat.
        /// </summary>
        public static string msrofat {
            get {
                return ResourceManager.GetString("msrofat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the expense.
        /// </summary>
        public static string Nameoftheexpense {
            get {
                return ResourceManager.GetString("Nameoftheexpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neighborhood.
        /// </summary>
        public static string neighborhood {
            get {
                return ResourceManager.GetString("neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add neighborhood.
        /// </summary>
        public static string neighborhood1 {
            get {
                return ResourceManager.GetString("neighborhood1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bills Exist Today !.
        /// </summary>
        public static string nobillsexisttoday {
            get {
                return ResourceManager.GetString("nobillsexisttoday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Groups To This Supervisor.
        /// </summary>
        public static string nogroupstothissupervisor {
            get {
                return ResourceManager.GetString("nogroupstothissupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pending Request Found !.
        /// </summary>
        public static string nopendingrequestfound {
            get {
                return ResourceManager.GetString("nopendingrequestfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not active.
        /// </summary>
        public static string notactive {
            get {
                return ResourceManager.GetString("notactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfBranches.
        /// </summary>
        public static string numofbranches {
            get {
                return ResourceManager.GetString("numofbranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Remaining.
        /// </summary>
        public static string oldrem {
            get {
                return ResourceManager.GetString("oldrem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out the warehouse.
        /// </summary>
        public static string outside {
            get {
                return ResourceManager.GetString("outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page table.
        /// </summary>
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string pagges {
            get {
                return ResourceManager.GetString("pagges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount paid.
        /// </summary>
        public static string paid {
            get {
                return ResourceManager.GetString("paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paid.
        /// </summary>
        public static string paid1 {
            get {
                return ResourceManager.GetString("paid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission date.
        /// </summary>
        public static string Permissiondate {
            get {
                return ResourceManager.GetString("Permissiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plz choose supplier.
        /// </summary>
        public static string plzchoosesupplier {
            get {
                return ResourceManager.GetString("plzchoosesupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A special claim for a string.
        /// </summary>
        public static string pp {
            get {
                return ResourceManager.GetString("pp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous balance.
        /// </summary>
        public static string previousbalance {
            get {
                return ResourceManager.GetString("previousbalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price menus.
        /// </summary>
        public static string pricemenu {
            get {
                return ResourceManager.GetString("pricemenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average price.
        /// </summary>
        public static string pricepr {
            get {
                return ResourceManager.GetString("pricepr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price Unity.
        /// </summary>
        public static string priceun {
            get {
                return ResourceManager.GetString("priceun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proces.
        /// </summary>
        public static string proces {
            get {
                return ResourceManager.GetString("proces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proces Number.
        /// </summary>
        public static string procesno {
            get {
                return ResourceManager.GetString("procesno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process.
        /// </summary>
        public static string process {
            get {
                return ResourceManager.GetString("process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoiceprusche.
        /// </summary>
        public static string prusche {
            get {
                return ResourceManager.GetString("prusche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return amount.
        /// </summary>
        public static string ramount {
            get {
                return ResourceManager.GetString("ramount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for discount.
        /// </summary>
        public static string Reasonfordiscount {
            get {
                return ResourceManager.GetString("Reasonfordiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rem Amount.
        /// </summary>
        public static string remamount {
            get {
                return ResourceManager.GetString("remamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable Person.
        /// </summary>
        public static string responperson {
            get {
                return ResourceManager.GetString("responperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Amount.
        /// </summary>
        public static string returnamount {
            get {
                return ResourceManager.GetString("returnamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        public static string Returns {
            get {
                return ResourceManager.GetString("Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Channels.
        /// </summary>
        public static string salechannel {
            get {
                return ResourceManager.GetString("salechannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Amount.
        /// </summary>
        public static string salesamount {
            get {
                return ResourceManager.GetString("salesamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesCode.
        /// </summary>
        public static string SalesCode {
            get {
                return ResourceManager.GetString("SalesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this page is to view sales items requests from general store .
        /// </summary>
        public static string saleswarehouserequestpagedescription {
            get {
                return ResourceManager.GetString("saleswarehouserequestpagedescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Branch.
        /// </summary>
        public static string selectBranch {
            get {
                return ResourceManager.GetString("selectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Company.
        /// </summary>
        public static string selectCompany {
            get {
                return ResourceManager.GetString("selectCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distributor.
        /// </summary>
        public static string selectdistributor {
            get {
                return ResourceManager.GetString("selectdistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select item.
        /// </summary>
        public static string Selectitem {
            get {
                return ResourceManager.GetString("Selectitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Supplier.
        /// </summary>
        public static string SelectSupplier {
            get {
                return ResourceManager.GetString("SelectSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tax.
        /// </summary>
        public static string Selecttax {
            get {
                return ResourceManager.GetString("Selecttax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select unit.
        /// </summary>
        public static string selectunity {
            get {
                return ResourceManager.GetString("selectunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller&apos;s price.
        /// </summary>
        public static string Sellersprice {
            get {
                return ResourceManager.GetString("Sellersprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sell price.
        /// </summary>
        public static string sellprice {
            get {
                return ResourceManager.GetString("sellprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial_No.
        /// </summary>
        public static string Serial_No {
            get {
                return ResourceManager.GetString("Serial_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settle.
        /// </summary>
        public static string Settle {
            get {
                return ResourceManager.GetString("Settle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settle Item.
        /// </summary>
        public static string Settle_Item {
            get {
                return ResourceManager.GetString("Settle Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Type.
        /// </summary>
        public static string SettlementType {
            get {
                return ResourceManager.GetString("SettlementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settle Returns.
        /// </summary>
        public static string SettleReturns {
            get {
                return ResourceManager.GetString("SettleReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift closure.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of Transaction.
        /// </summary>
        public static string Size_of_Transaction {
            get {
                return ResourceManager.GetString("Size of Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the special price.
        /// </summary>
        public static string specialprice {
            get {
                return ResourceManager.GetString("specialprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add Region.
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name Region.
        /// </summary>
        public static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of expense.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm receipt of the goods.
        /// </summary>
        public static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delivery of the goods.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperVisor.
        /// </summary>
        public static string supervisor {
            get {
                return ResourceManager.GetString("supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Name.
        /// </summary>
        public static string supervisorname {
            get {
                return ResourceManager.GetString("supervisorname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisors.
        /// </summary>
        public static string supervisors {
            get {
                return ResourceManager.GetString("supervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supplier.
        /// </summary>
        public static string supplier1 {
            get {
                return ResourceManager.GetString("supplier1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Price.
        /// </summary>
        public static string supplierprice {
            get {
                return ResourceManager.GetString("supplierprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this page is to setting suppliers or disable them or add new one.
        /// </summary>
        public static string supsettingpage {
            get {
                return ResourceManager.GetString("supsettingpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Sure to Delete ? .
        /// </summary>
        public static string suredeleteagent {
            get {
                return ResourceManager.GetString("suredeleteagent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount after Vat.
        /// </summary>
        public static string taavat {
            get {
                return ResourceManager.GetString("taavat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tax.
        /// </summary>
        public static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bill After Discount.
        /// </summary>
        public static string tbafterdiscount {
            get {
                return ResourceManager.GetString("tbafterdiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bill Before Discount.
        /// </summary>
        public static string tbbeforediscount {
            get {
                return ResourceManager.GetString("tbbeforediscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bill Discount.
        /// </summary>
        public static string tbdiscount {
            get {
                return ResourceManager.GetString("tbdiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the document.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cashier.
        /// </summary>
        public static string Thecashier {
            get {
                return ResourceManager.GetString("Thecashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the rest.
        /// </summary>
        public static string therest {
            get {
                return ResourceManager.GetString("therest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Item Count.
        /// </summary>
        public static string titemcount {
            get {
                return ResourceManager.GetString("titemcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Item Discount .
        /// </summary>
        public static string titemdiscount {
            get {
                return ResourceManager.GetString("titemdiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Details.
        /// </summary>
        public static string todaydetails {
            get {
                return ResourceManager.GetString("todaydetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Action.
        /// </summary>
        public static string totalaction {
            get {
                return ResourceManager.GetString("totalaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total paid.
        /// </summary>
        public static string Totalpaid {
            get {
                return ResourceManager.GetString("Totalpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bill.
        /// </summary>
        public static string totalpil {
            get {
                return ResourceManager.GetString("totalpil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bill Agil.
        /// </summary>
        public static string totalpilagil {
            get {
                return ResourceManager.GetString("totalpilagil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bill Cash.
        /// </summary>
        public static string totalpilcash {
            get {
                return ResourceManager.GetString("totalpilcash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bill Net.
        /// </summary>
        public static string totalpilnet {
            get {
                return ResourceManager.GetString("totalpilnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string totalprice {
            get {
                return ResourceManager.GetString("totalprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again !!.
        /// </summary>
        public static string tryagain {
            get {
                return ResourceManager.GetString("tryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type expense.
        /// </summary>
        public static string typeex {
            get {
                return ResourceManager.GetString("typeex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type tt.
        /// </summary>
        public static string typett {
            get {
                return ResourceManager.GetString("typett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid Deffered.
        /// </summary>
        public static string unpaiddefferd {
            get {
                return ResourceManager.GetString("unpaiddefferd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity.
        /// </summary>
        public static string untiy {
            get {
                return ResourceManager.GetString("untiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this page is to view Sales new account requests .
        /// </summary>
        public static string userregistrationrequest {
            get {
                return ResourceManager.GetString("userregistrationrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Registration Requests.
        /// </summary>
        public static string UsersRegistrationRequests {
            get {
                return ResourceManager.GetString("UsersRegistrationRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string vat {
            get {
                return ResourceManager.GetString("vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Bills.
        /// </summary>
        public static string viewbills {
            get {
                return ResourceManager.GetString("viewbills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this page is to add or receive counts of items from general store .
        /// </summary>
        public static string warehousepagemsg {
            get {
                return ResourceManager.GetString("warehousepagemsg", resourceCulture);
            }
        }
    }
}
